version: "3.9"

services:
  cms:
    image: public.ecr.aws/ds/websight-cms-starter:1.19.1
    ports:
      - "8080:8080"
    environment:
      WS_ADMIN_USERNAME: "wsadmin"
      MONGODB_HOST: "mongo"
      MONGODB_PORT: 27017
      LEASE_CHECK_MODE: "LENIENT"
    volumes:
      - cms_logs:/websight/logs
      - site_repository:/websight/docroot
    depends_on:
      - mongo
  nginx:
    image: public.ecr.aws/ds/websight-nginx-starter:1.19.1
    ports:
      - "80:80"
    volumes:
      - site_repository:/usr/share/nginx/html:ro
  mongo:
    image: mongo:4.4.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
    volumes:
      - mongo_repository:/data/db

volumes:
  cms_logs:
  mongo_repository:
  site_repository:
