apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  name: websight-cms-${ENV_NAME_POSTFIX}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        run.googleapis.com/startupProbeType: Custom
    spec:
      containers:
      - args:
          - websight-cms-starter-tar
        image: ${IMAGE_REGISTRY}/websight-cms-starter:${IMAGE_TAG}
        # image: europe-west1-docker.pkg.dev/websight-dxp-development/cms-starter/websight-cms-starter
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /system/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
        env:
          - name: TEST
            value: /run/secrets/admin.password
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /system/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /run/secrets
          name: websight-admin-password-volume
          readOnly: true
        - mountPath: /websight/repository
          name: repository-volume
      timeoutSeconds: 300
      volumes:
      - name: websight-admin-password-volume
        secret:
          items:
          - key: latest
            path: admin.password
          secretName: websight-admin-password
      - name: repository-volume
        emptyDir:
          sizeLimit: 2Gi
          medium: Memory
  traffic:
  - latestRevision: true
    percent: 100
