apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
  labels:
    cloud.googleapis.com/location: europe-west1
  name: websight-cms-tomaszmichalak
  namespace: '1058091587080'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '1'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: 6da15545-7c3e-423c-9ec6-efda3b2be528
        run.googleapis.com/startupProbeType: Custom
    spec:
      containerConcurrency: 80
      containers:
      - args:
        - websight-cms-starter-tar
        image: tomaszmichalak/websight-cms-starter
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /system/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: 2000m
            memory: 2Gi
        startupProbe:
          failureThreshold: 3
          httpGet:
            path: /system/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /run/secrets/admin.password
          name: secret-878a4854-d0ae-49e0-8787-034940ac5e5f
          readOnly: true
      serviceAccountName: 1058091587080-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
      volumes:
      - name: secret-878a4854-d0ae-49e0-8787-034940ac5e5f
        secret:
          items:
          - key: latest
            path: Default_CMS_starter_admin_password
          secretName: Default_CMS_starter_admin_password
  traffic:
  - latestRevision: true
    percent: 100
